services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: smartt
      MYSQL_DATABASE: smartt-graph
    volumes: 
      - ./db/data:/var/lib/mysql
  python:
    build:
      "./src"
    volumes:
      - ./src:/usr/src/app
    restart: always
    depends_on:
      - db